# Generated by Django 5.1.6 on 2025-03-25 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institute', '0002_initial'),
        ('teacher', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.subject'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='teacher.exam'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examtemplate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examtemplate',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.subject'),
        ),
        migrations.AddField(
            model_name='exam',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='teacher.examtemplate'),
        ),
        migrations.AddField(
            model_name='question',
            name='exam',
            field=models.ForeignKey(help_text='The exam this question is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='teacher.exam'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='exam',
            field=models.ForeignKey(help_text='The exam this answer pertains to.', on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='teacher.exam'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='teacher.question'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['exam', 'completed'], name='teacher_exa_exam_id_fec242_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examattempt',
            unique_together={('student', 'exam')},
        ),
        migrations.AddIndex(
            model_name='examtemplate',
            index=models.Index(fields=['subject', 'difficulty_level'], name='teacher_exa_subject_249f54_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['date', 'start_time'], name='teacher_exa_date_7732d4_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['status', 'is_published'], name='teacher_exa_status_066290_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('exam', 'order')},
        ),
        migrations.AddIndex(
            model_name='studentanswer',
            index=models.Index(fields=['exam', 'student'], name='teacher_stu_exam_id_57a877_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentanswer',
            unique_together={('student', 'question', 'exam')},
        ),
    ]
