# Generated by Django 5.1.6 on 2025-03-11 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_examtemplate_exam_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='ai_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='ai_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
