# Generated by Django 5.1.6 on 2025-03-07 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_is_profile_user_is_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_institute',
            field=models.BooleanField(default=False, verbose_name='Is institute'),
        ),
    ]
