# Generated by Django 5.1.6 on 2025-03-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('STF', 'Staff'), ('PRD', 'Product'), ('CRY', 'Category'), ('CUS', 'Customer'), ('OFR', 'Offer'), ('ORD', 'Order')], max_length=50)),
                ('number', models.CharField(max_length=100)),
            ],
        ),
    ]
