# Generated by Django 5.1.6 on 2025-03-03 18:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_examattempt'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='studentanswer',
            name='testapp_stu_student_404cb7_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentanswer',
            name='testapp_stu_score_0f766b_idx',
        ),
        migrations.AlterField(
            model_name='exam',
            name='duration',
            field=models.IntegerField(help_text='Minutes', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(480)]),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True),
        ),
    ]
