# Generated by Django 5.1.6 on 2025-03-25 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='malpracticelog',
            name='exam',
            field=models.ForeignKey(help_text='The exam during which the malpractice occurred.', on_delete=django.db.models.deletion.CASCADE, related_name='malpractice_logs', to='teacher.exam'),
        ),
    ]
