# Generated by Django 5.1.6 on 2025-03-25 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='malpracticelog',
            name='student',
            field=models.ForeignKey(blank=True, help_text='The student responsible for the malpractice, if identifiable.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='malpractice_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='malpracticelog',
            index=models.Index(fields=['exam', 'attempt_uuid'], name='student_mal_exam_id_63a0ef_idx'),
        ),
        migrations.AddIndex(
            model_name='malpracticelog',
            index=models.Index(fields=['type', 'severity'], name='student_mal_type_735c46_idx'),
        ),
    ]
