# Generated by Django 5.1.6 on 2025-03-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='classes',
            field=models.ManyToManyField(blank=True, to='institute.class'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='institute.subject'),
        ),
    ]
