# Generated by Django 5.1.6 on 2025-03-11 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0005_alter_teacherprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='institute.institution'),
        ),
    ]
